# Generated by Django 4.2.14 on 2024-08-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtracking',
            name='email_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.list'),
        ),
    ]
