# Generated by Django 4.2.14 on 2024-08-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockanalysis', '0002_stockdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='week_52_lose',
            new_name='week_52_low',
        ),
    ]
